
obj-$(CONFIG_NPU_DEVDRV) += platform/
obj-$(CONFIG_NPU_DEVDRV) += manager/
obj-$(CONFIG_NPU_DEVDRV) += device/
obj-$(CONFIG_NPU_HISI_ATF_SEVICES) += facility/atf/
obj-$(CONFIG_NPU_DEVDRV) += dfx/log/
obj-$(CONFIG_NPU_DEVDRV) += dfx/dbg/
obj-$(CONFIG_NPU_DEVDRV) += dfx/profiling/
obj-$(CONFIG_NPU_DEVDRV) += facility/


