/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "plat_effect_para.h"

#include "spn_boe_nt36672a_6p26_2.h"

#include "jny_boe_nt36672a_6p4.h"

#include "jny_boe_td4320_6p4.h"

#include "jny_tm_td4320_6p4.h"

#include "jny_tm_nt36672a_6p4.h"

#include "udp_boe_td4320_udp.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
SEA_SAMSUNG_EA8076_PANEL,
SEA_V4_SAMSUNG_EA8076_PANEL,
SEA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
HLK_TCL_NT36682A_6P59_PANEL,
HLK_BOE_TD4320_6P59_PANEL,
HLK_TM_TD4321_6P59_PANEL,
HLK_INX_NT36682A_6P59_PANEL,
HLK_TM_NT36682A_6P59_PANEL,
HLK_BOE_NT36682A_6P59_PANEL,
HLK_BOE_NT36682A_6P59_2_PANEL,
HLK_TCL_NT36682A_6P59_2_PANEL,
HLK_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
SPN_TM_TD4320_6P26_2_PANEL,
SPN_CTC_NT36672A_6P26_2_PANEL,
SPN_CTC_FT8719_6P26_2_PANEL,
SPN_LG_TD4320_6P26_2_PANEL,
SPN_BOE_NT36672A_6P26_2_PANEL,
SPN_TM_NT36672A_6P26_2_PANEL,
SPN_BOE_TD4321_6P26_PANEL,
SPN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
YAL_BOE_NT36672A_6P26_PANEL,
YAL_CTC_NT36672A_6P26_PANEL,
YAL_CTC_FT8719_6P26_PANEL,
YAL_TM_TD4320_6P26_PANEL,
YAL_TM_NT36672A_6P26_PANEL,
YAL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
BAH3_BOE_HX83102H_10P3_VIDEO_PANEL,
BAH3_INX_HX83102H_10P3_VIDEO_PANEL,
BAH3_BOE_HX83102H_10P3_VIDEO_2_PANEL,
BAH3_BOE_NT36523_10P3_VIDEO_PANEL,
BAH3_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
JNY_BOE_NT36672A_6P4_PANEL,
JNY_BOE_TD4320_6P4_PANEL,
JNY_TM_TD4320_6P4_PANEL,
JNY_TM_NT36672A_6P4_PANEL,
JNY_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
AQM_SAMSUNG_8FC1_6P3_PANEL,
AQM_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
FRL_TCL_NT36682C_6P63_PANEL,
FRL_INX_FT8720_6P63_PANEL,
FRL_TM_NT36682C_6P63_PANEL,
FRL_BOE_NT36682C_6P63_PANEL,
FRL_INX_NT36682C_6P63_PANEL,
FRL_BOE_FT8720_6P63_PANEL,
FRL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
UDP_BOE_TD4320_UDP_PANEL,
UDP_AUTO_FAKE_PANEL_UDP_DEF_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcd_kit_board_map {
    uint8_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcd_kit_board_map lcd_kit_map[] = {
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {SEA_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 1000},
    {SEA_V4_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 1001},
    {SEA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {HLK_TCL_NT36682A_6P59_PANEL, "tcl_nt36682a_6p59_1080p_video", 2000},
    {HLK_BOE_TD4320_6P59_PANEL, "boe_td4320_6p59_1080p_video", 2000},
    {HLK_TM_TD4321_6P59_PANEL, "tm_td4321_6p59_1080p_video", 2000},
    {HLK_INX_NT36682A_6P59_PANEL, "inx_nt36682a_6p59_1080p_video", 2000},
    {HLK_TM_NT36682A_6P59_PANEL, "tm_nt36682a_6p59_1080p_video", 2000},
    {HLK_BOE_NT36682A_6P59_PANEL, "boe_nt36682a_6p59_1080p_video", 2000},
    {HLK_BOE_NT36682A_6P59_2_PANEL, "boe_nt36682a_6p59_1080p_video_vn2", 2000},
    {HLK_TCL_NT36682A_6P59_2_PANEL, "tcl_nt36682a_6p59_1080p_video_vn2", 2000},
    {HLK_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {SPN_TM_TD4320_6P26_2_PANEL, "tm_td4320_6p26_1080p_video", 3000},
    {SPN_CTC_NT36672A_6P26_2_PANEL, "ctc_nt36672a_6p26_1080p_video", 3000},
    {SPN_CTC_FT8719_6P26_2_PANEL, "ctc_ft8719_6p26_1080p_video", 3000},
    {SPN_LG_TD4320_6P26_2_PANEL, "lg_td4320_6p26_1080p_video", 3000},
    {SPN_BOE_NT36672A_6P26_2_PANEL, "boe_nt36672a_6p26_1080p_video", 3000},
    {SPN_TM_NT36672A_6P26_2_PANEL, "tm_nt36672a_6p26_1080p_video", 3000},
    {SPN_BOE_TD4321_6P26_PANEL, "boe_td4321_6p26_1080p_video", 3000},
    {SPN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {YAL_BOE_NT36672A_6P26_PANEL, "boe_nt36672a_6p26", 4000},
    {YAL_CTC_NT36672A_6P26_PANEL, "ctc_nt36672a_6p26", 4000},
    {YAL_CTC_FT8719_6P26_PANEL, "ctc_ft8719_6p26", 4000},
    {YAL_TM_TD4320_6P26_PANEL, "tm_td4320_6p26", 4000},
    {YAL_TM_NT36672A_6P26_PANEL, "tm_nt36672a_6p26", 4000},
    {YAL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {BAH3_BOE_HX83102H_10P3_VIDEO_PANEL, "boe_hx83102h_10p3_video", 5000},
    {BAH3_INX_HX83102H_10P3_VIDEO_PANEL, "inx_hx83102h_10p3_video", 5000},
    {BAH3_BOE_HX83102H_10P3_VIDEO_2_PANEL, "boe_hx83102h_10p3_video", 5000},
    {BAH3_BOE_NT36523_10P3_VIDEO_PANEL, "boe_nt36523_10p3_video", 5000},
    {BAH3_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {JNY_BOE_NT36672A_6P4_PANEL, "boe_nt36672a_6p4", 6000},
    {JNY_BOE_TD4320_6P4_PANEL, "boe_td4320_6p4", 6000},
    {JNY_TM_TD4320_6P4_PANEL, "tm_td4320_6p4", 6000},
    {JNY_TM_NT36672A_6P4_PANEL, "tm_nt36672a_6p4", 6000},
    {JNY_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {AQM_SAMSUNG_8FC1_6P3_PANEL, "samsung_8fc1_6p3_1080p_video", 7000},
    {AQM_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {FRL_TCL_NT36682C_6P63_PANEL, "tcl_nt36682c_6p63_1080p_video", 7000},
    {FRL_INX_FT8720_6P63_PANEL, "inx_ft8720_6p63_1080p_video", 7000},
    {FRL_TM_NT36682C_6P63_PANEL, "tm_nt36682c_6p63_1080p_video", 7000},
    {FRL_BOE_NT36682C_6P63_PANEL, "boe_nt36682c_6p63_1080p_video", 7000},
    {FRL_INX_NT36682C_6P63_PANEL, "inx_nt36682c_6p63_1080p_video", 7000},
    {FRL_BOE_FT8720_6P63_PANEL, "boe_ft8720_6p63_1080p_video", 7000},
    {FRL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {UDP_BOE_TD4320_UDP_PANEL, "boe_td4320_udp", 30},
    {UDP_AUTO_FAKE_PANEL_UDP_DEF_PANEL, "auto_fake_panel_udp-def", 30},
};

static void lcd_kit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    if (pinfo->gamma_support == 1)
    {
        pinfo->gamma_lut_table_R = plat_gamma_lut_table_R;
        pinfo->gamma_lut_table_G = plat_gamma_lut_table_G;
        pinfo->gamma_lut_table_B = plat_gamma_lut_table_B;
        pinfo->gamma_lut_table_len = ARRAY_SIZE(plat_gamma_lut_table_R);
        pinfo->igm_lut_table_R = plat_igm_lut_table_R;
        pinfo->igm_lut_table_G = plat_igm_lut_table_G;
        pinfo->igm_lut_table_B = plat_igm_lut_table_B;
        pinfo->igm_lut_table_len = ARRAY_SIZE(plat_igm_lut_table_R);
        pinfo->gmp_lut_table_low32bit = &plat_gmp_lut_table_low32bit[0][0][0];
        pinfo->gmp_lut_table_high4bit = &plat_gmp_lut_table_high4bit[0][0][0];
        pinfo->gmp_lut_table_len = ARRAY_3_SIZE(plat_gmp_lut_table_low32bit);
        pinfo->xcc_table = plat_xcc_table;
        pinfo->xcc_table_len = ARRAY_SIZE(plat_xcc_table);
    }
    switch (panel_id) {
    case SPN_BOE_NT36672A_6P26_2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = spn_boe_nt36672a_6p26_2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = spn_boe_nt36672a_6p26_2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = spn_boe_nt36672a_6p26_2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(spn_boe_nt36672a_6p26_2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = spn_boe_nt36672a_6p26_2_igm_lut_table_R;
            pinfo->igm_lut_table_G = spn_boe_nt36672a_6p26_2_igm_lut_table_G;
            pinfo->igm_lut_table_B = spn_boe_nt36672a_6p26_2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(spn_boe_nt36672a_6p26_2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &spn_boe_nt36672a_6p26_2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &spn_boe_nt36672a_6p26_2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(spn_boe_nt36672a_6p26_2_gmp_lut_table_low32bit);
            pinfo->xcc_table = spn_boe_nt36672a_6p26_2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(spn_boe_nt36672a_6p26_2_xcc_table);
        }
        break;
    case JNY_BOE_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = jny_boe_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = jny_boe_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = jny_boe_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(jny_boe_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = jny_boe_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = jny_boe_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = jny_boe_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(jny_boe_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &jny_boe_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &jny_boe_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(jny_boe_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = jny_boe_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(jny_boe_nt36672a_6p4_xcc_table);
        }
        break;
    case JNY_BOE_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = jny_boe_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = jny_boe_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = jny_boe_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(jny_boe_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = jny_boe_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = jny_boe_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = jny_boe_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(jny_boe_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &jny_boe_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &jny_boe_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(jny_boe_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = jny_boe_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(jny_boe_td4320_6p4_xcc_table);
        }
        break;
    case JNY_TM_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = jny_tm_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = jny_tm_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = jny_tm_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(jny_tm_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = jny_tm_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = jny_tm_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = jny_tm_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(jny_tm_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &jny_tm_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &jny_tm_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(jny_tm_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = jny_tm_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(jny_tm_td4320_6p4_xcc_table);
        }
        break;
    case JNY_TM_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = jny_tm_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = jny_tm_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = jny_tm_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(jny_tm_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = jny_tm_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = jny_tm_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = jny_tm_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(jny_tm_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &jny_tm_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &jny_tm_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(jny_tm_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = jny_tm_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(jny_tm_nt36672a_6p4_xcc_table);
        }
        break;
    case UDP_BOE_TD4320_UDP_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = udp_boe_td4320_udp_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = udp_boe_td4320_udp_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = udp_boe_td4320_udp_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(udp_boe_td4320_udp_gamma_lut_table_R);
            pinfo->igm_lut_table_R = udp_boe_td4320_udp_igm_lut_table_R;
            pinfo->igm_lut_table_G = udp_boe_td4320_udp_igm_lut_table_G;
            pinfo->igm_lut_table_B = udp_boe_td4320_udp_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(udp_boe_td4320_udp_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &udp_boe_td4320_udp_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &udp_boe_td4320_udp_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(udp_boe_td4320_udp_gmp_lut_table_low32bit);
            pinfo->xcc_table = udp_boe_td4320_udp_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(udp_boe_td4320_udp_xcc_table);
        }
        break;
    default:
        LCD_KIT_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcd_kit_get_panel_id(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcd_kit_map); ++i) {
        length = strlen(lcd_kit_map[i].panel_compatible);
        if ((lcd_kit_map[i].product_id == product_id) && !strncmp(lcd_kit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcd_kit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
