obj-$(CONFIG_HUAWEI_CHARGER_AP) += charger_ic/
obj-$(CONFIG_BOOST_5V) += boost_5v/
obj-$(CONFIG_BUCKBOOST) += buck_boost/
obj-$(CONFIG_CHARGE_PUMP) += charge_pump/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_ic/
