#ifndef __SOC_EFUSE_INTERFACE_H__
#define __SOC_EFUSE_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#define EFUSE_ATTR_READABLE (0x00000001UL)
#define EFUSE_ATTR_READ_DEVICE (0x00000002UL)
#define EFUSE_ATTR_READ_SRAM (0x00000004UL)
#define EFUSE_ATTR_READ_ZERO (0x00000008UL)
#define EFUSE_ATTR_WRITEABLE (0x00000100UL)
#define EFUSE_ATTR_WRITE_NOT_UPDATE (0x00000200UL)
#define EFUSE_ATTR_WRITE_CHECK (0x00000400UL)
typedef struct {
 unsigned int start_bit;
 unsigned int bit_cnt;
 unsigned int id;
 unsigned int attr;
} efuse_attr_t;
enum {
 HUK_VALUE = 0,
 SCP_VALUE,
 MP_FLAG,
 HUK_ZEROES,
 SCP_ZEROES,
 OEMP_FLAG,
 KCE_VALUE,
 HBK0_VALUE,
 HBK1_VALUE,
 TRB_COUNTER,
 NTRB_COUNTER = 10,
 EKCST_VALUE,
 EKCST_ZEROES,
 DIEID_VALUE,
 DIEID_LOTID_VALUE,
 DIEID_WAFERID_VALUE,
 DIEID_DIEX_VALUE,
 DIEID_DIEY_VALUE,
 DIEID_RT_FT_VALUE,
 IDDQ_VALUE,
 IDDQ_ARTEMIS_VALUE = 20,
 IDDQ_A53_VALUE,
 IDDQ_GPU_VALUE,
 IDDQ_SYS_VALUE,
 IDDQ_PERI_VALUE,
 TENSOR_TRIM,
 TENSOR_REF_TRIM,
 HPM_TRIM,
 SPEED_GRADE,
 SLT_FINISH,
 SOFT_COUNTER = 30,
 MODEM_HUK,
 MODEM_HUKZEROES,
 DMHASH_VALUE,
 CARRI_INFO,
 FLASH_COUNT,
 DDR_FREQ_ATE,
 INSE_FLAG,
 DDR_FREQ_SLT,
 CHIP_LEVEL,
 CHIP_ID = 40,
 AUTH_KEY,
 EFUSE_HISEE_EFUSE1,
 CHIPID_VLD,
 EFUSE_HISEE_EFUSE2,
 EFUSE_HISEE_EFUSE3,
 EFUSE_DJTAG_CTRL,
 SECENGDBG_BYPASS,
 CHIPIDDFTKEY_ZEROES,
 MODEM_DBGBYPASS,
 PAD_DISABLE = 50,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_DFTRD_DISABLE,
 EFUSE_SECDBG_CTRL,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 SECDBG_DSPJTAGDIS = 60,
 SHUTDOWN_SWINGCARD,
 SECENG_EKCSTRDEN,
 KPRTLRD_DISABLE,
 DX_CLKEN,
 EFUSE_MODEM_AVSPASS,
 EFUSE_MODEM_BYPASS,
 EFUSE_USB20PHY_VSEL,
};
#define EFUSE_HUK_VALUE_START 0
#define EFUSE_HUK_VALUE_SIZE 256
#define EFUSE_SCP_VALUE_START 256
#define EFUSE_SCP_VALUE_SIZE 64
#define EFUSE_MP_FLAG_START 320
#define EFUSE_MP_FLAG_SIZE 32
#define EFUSE_HUK_ZEROES_START 320
#define EFUSE_HUK_ZEROES_SIZE 8
#define EFUSE_SCP_ZEROES_START 328
#define EFUSE_SCP_ZEROES_SIZE 7
#define EFUSE_OEMP_FLAG_START 352
#define EFUSE_OEMP_FLAG_SIZE 32
#define EFUSE_KCE_VALUE_START 384
#define EFUSE_KCE_VALUE_SIZE 128
#define EFUSE_HBK0_VALUE_START 512
#define EFUSE_HBK0_VALUE_SIZE 128
#define EFUSE_HBK1_VALUE_START 640
#define EFUSE_HBK1_VALUE_SIZE 128
#define EFUSE_TRB_COUNTER_START 768
#define EFUSE_TRB_COUNTER_SIZE 32
#define EFUSE_NTRB_COUNTER_START 800
#define EFUSE_NTRB_COUNTER_SIZE 224
#define EFUSE_EKCST_VALUE_START 1024
#define EFUSE_EKCST_VALUE_SIZE 128
#define EFUSE_EKCST_ZEROES_START 1152
#define EFUSE_EKCST_ZEROES_SIZE 32
#define EFUSE_DIEID_VALUE_START 1184
#define EFUSE_DIEID_VALUE_SIZE 160
#define EFUSE_DIEID_LOTID_VALUE_START 1188
#define EFUSE_DIEID_LOTID_VALUE_SIZE 36
#define EFUSE_DIEID_WAFERID_VALUE_START 1224
#define EFUSE_DIEID_WAFERID_VALUE_SIZE 5
#define EFUSE_DIEID_DIEX_VALUE_START 1229
#define EFUSE_DIEID_DIEX_VALUE_SIZE 8
#define EFUSE_DIEID_DIEY_VALUE_START 1237
#define EFUSE_DIEID_DIEY_VALUE_SIZE 8
#define EFUSE_DIEID_RT_FT_VALUE_START 1312
#define EFUSE_DIEID_RT_FT_VALUE_SIZE 1
#define EFUSE_IDDQ_VALUE_START 1344
#define EFUSE_IDDQ_VALUE_SIZE 50
#define EFUSE_IDDQ_ARTEMIS_VALUE_START 1344
#define EFUSE_IDDQ_ARTEMIS_VALUE_SIZE 10
#define EFUSE_IDDQ_A53_VALUE_START 1354
#define EFUSE_IDDQ_A53_VALUE_SIZE 10
#define EFUSE_IDDQ_GPU_VALUE_START 1364
#define EFUSE_IDDQ_GPU_VALUE_SIZE 10
#define EFUSE_IDDQ_SYS_VALUE_START 1374
#define EFUSE_IDDQ_SYS_VALUE_SIZE 10
#define EFUSE_IDDQ_PERI_VALUE_START 1384
#define EFUSE_IDDQ_PERI_VALUE_SIZE 10
#define EFUSE_TENSOR_TRIM_START 1394
#define EFUSE_TENSOR_TRIM_SIZE 55
#define EFUSE_TENSOR_REF_TRIM_START 1394
#define EFUSE_TENSOR_REF_TRIM_SIZE 11
#define EFUSE_HPM_TRIM_START 1449
#define EFUSE_HPM_TRIM_SIZE 10
#define EFUSE_SPEED_GRADE_START 1624
#define EFUSE_SPEED_GRADE_SIZE 20
#define EFUSE_SLT_FINISH_START 1644
#define EFUSE_SLT_FINISH_SIZE 3
#define EFUSE_SOFT_COUNTER_START 1647
#define EFUSE_SOFT_COUNTER_SIZE 32
#define EFUSE_MODEM_HUK_START 1679
#define EFUSE_MODEM_HUK_SIZE 128
#define EFUSE_MODEM_HUKZEROES_START 1807
#define EFUSE_MODEM_HUKZEROES_SIZE 8
#define EFUSE_DMHASH_VALUE_START 1815
#define EFUSE_DMHASH_VALUE_SIZE 1
#define EFUSE_CARRI_INFO_START 1816
#define EFUSE_CARRI_INFO_SIZE 88
#define EFUSE_FLASH_COUNT_START 1904
#define EFUSE_FLASH_COUNT_SIZE 8
#define EFUSE_DDR_FREQ_ATE_START 2408
#define EFUSE_DDR_FREQ_ATE_SIZE 8
#define EFUSE_INSE_FLAG_START 2416
#define EFUSE_INSE_FLAG_SIZE 2
#define EFUSE_DDR_FREQ_SLT_START 2418
#define EFUSE_DDR_FREQ_SLT_SIZE 8
#define EFUSE_CHIP_LEVEL_START 3836
#define EFUSE_CHIP_LEVEL_SIZE 2
#define EFUSE_CHIP_ID_START 3872
#define EFUSE_CHIP_ID_SIZE 64
#define EFUSE_AUTH_KEY_START 3936
#define EFUSE_AUTH_KEY_SIZE 64
#define EFUSE_HISEE_EFUSE1_START 4000
#define EFUSE_HISEE_EFUSE1_SIZE 32
#define EFUSE_CHIPID_VLD_START 4032
#define EFUSE_CHIPID_VLD_SIZE 1
#define EFUSE_HISEE_EFUSE2_START 4036
#define EFUSE_HISEE_EFUSE2_SIZE 9
#define EFUSE_HISEE_EFUSE3_START 4046
#define EFUSE_HISEE_EFUSE3_SIZE 2
#define EFUSE_DJTAG_CTRL_START 4050
#define EFUSE_DJTAG_CTRL_SIZE 2
#define EFUSE_SECENGDBG_BYPASS_START 4052
#define EFUSE_SECENGDBG_BYPASS_SIZE 1
#define EFUSE_CHIPIDDFTKEY_ZEROES_START 4053
#define EFUSE_CHIPIDDFTKEY_ZEROES_SIZE 8
#define EFUSE_MODEM_DBGBYPASS_START 4061
#define EFUSE_MODEM_DBGBYPASS_SIZE 1
#define EFUSE_PAD_DISABLE_START 4065
#define EFUSE_PAD_DISABLE_SIZE 1
#define EFUSE_HISEE_EFUSE4_START 4068
#define EFUSE_HISEE_EFUSE4_SIZE 2
#define EFUSE_HUKRD_DISABLE_START 4070
#define EFUSE_HUKRD_DISABLE_SIZE 1
#define EFUSE_SCPRD_DISABLE_START 4071
#define EFUSE_SCPRD_DISABLE_SIZE 1
#define EFUSE_DFTRD_DISABLE_START 4072
#define EFUSE_DFTRD_DISABLE_SIZE 1
#define EFUSE_SECDBG_CTRL_START 4073
#define EFUSE_SECDBG_CTRL_SIZE 2
#define EFUSE_SECDBG_DBGEN_START 4075
#define EFUSE_SECDBG_DBGEN_SIZE 1
#define EFUSE_SECDBG_NIDEN_START 4076
#define EFUSE_SECDBG_NIDEN_SIZE 1
#define EFUSE_SECDBG_SPIDEN_START 4077
#define EFUSE_SECDBG_SPIDEN_SIZE 1
#define EFUSE_SECDBG_SPNIDEN_START 4078
#define EFUSE_SECDBG_SPNIDEN_SIZE 1
#define EFUSE_SECDBG_DSPJTAGDIS_START 4079
#define EFUSE_SECDBG_DSPJTAGDIS_SIZE 1
#define EFUSE_SHUTDOWN_SWINGCARD_START 4081
#define EFUSE_SHUTDOWN_SWINGCARD_SIZE 2
#define EFUSE_SECENG_EKCSTRDEN_START 4083
#define EFUSE_SECENG_EKCSTRDEN_SIZE 1
#define EFUSE_KPRTLRD_DISABLE_START 4084
#define EFUSE_KPRTLRD_DISABLE_SIZE 1
#define EFUSE_DX_CLKEN_START 4092
#define EFUSE_DX_CLKEN_SIZE 1
#define EFUSE_MODEM_AVSPASS_START 1613
#define EFUSE_MODEM_AVSPASS_SIZE 2
#define EFUSE_MODEM_BYPASS_START 2832
#define EFUSE_MODEM_BYPASS_SIZE 2
#define EFUSE_USB20PHY_VSEL_START 4085
#define EFUSE_USB20PHY_VSEL_SIZE 1
#define EFUSE_MAX_SIZE 4096
#define EFUSE_ITEM_MAX 256
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
