obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_soh.o
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_basp.o
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_asw.o
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_iscd.o
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_cfsd.o
