//****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co., Ltd.
// File name     :  axi_jpeg_reg_offset_field.h
// Author        :  AnthonySixta
// Version       :  1.0 
// Date          :  2018-01-03
// Description   :  Define all registers/tables for HiStarISP
// Others        :  Generated automatically by nManager V4.2 
// History       :  AnthonySixta 2018-01-03 Create file
//******************************************************************************

#ifndef __AXI_JPEG_REG_OFFSET_FIELD_H__
#define __AXI_JPEG_REG_OFFSET_FIELD_H__

#define AXI_JPEG_MAX_AXIWRITE_ID_LEN          5  
#define AXI_JPEG_MAX_AXIWRITE_ID_OFFSET       24 
#define AXI_JPEG_MAX_AXIREAD_ID_LEN           5  
#define AXI_JPEG_MAX_AXIREAD_ID_OFFSET        16 
#define AXI_JPEG_DU_THRESHOLD_REACHED_LEN     8  
#define AXI_JPEG_DU_THRESHOLD_REACHED_OFFSET  8  
#define AXI_JPEG_AXIWRITE_DU_THRESHOLD_LEN    6  
#define AXI_JPEG_AXIWRITE_DU_THRESHOLD_OFFSET 0  

#define AXI_JPEG_RD_PEAK_EN_LEN    1  
#define AXI_JPEG_RD_PEAK_EN_OFFSET 8  
#define AXI_JPEG_WR_PEAK_EN_LEN    1  
#define AXI_JPEG_WR_PEAK_EN_OFFSET 0  

#define AXI_JPEG_RD_PEAK_LEN       8  
#define AXI_JPEG_RD_PEAK_OFFSET    8  
#define AXI_JPEG_WR_PEAK_LEN       8  
#define AXI_JPEG_WR_PEAK_OFFSET    0  

#define AXI_JPEG_WR_QOS_SR_LEN                    2  
#define AXI_JPEG_WR_QOS_SR_OFFSET                 30 
#define AXI_JPEG_WR_QOS_MAX_LEN                   2  
#define AXI_JPEG_WR_QOS_MAX_OFFSET                28 
#define AXI_JPEG_WR_QOS_MIN_LEN                   2  
#define AXI_JPEG_WR_QOS_MIN_OFFSET                26 
#define AXI_JPEG_WR_QOS_THRESHOLD_11_START_LEN    4  
#define AXI_JPEG_WR_QOS_THRESHOLD_11_START_OFFSET 20 
#define AXI_JPEG_WR_QOS_THRESHOLD_11_STOP_LEN     4  
#define AXI_JPEG_WR_QOS_THRESHOLD_11_STOP_OFFSET  16 
#define AXI_JPEG_WR_QOS_THRESHOLD_10_START_LEN    4  
#define AXI_JPEG_WR_QOS_THRESHOLD_10_START_OFFSET 12 
#define AXI_JPEG_WR_QOS_THRESHOLD_10_STOP_LEN     4  
#define AXI_JPEG_WR_QOS_THRESHOLD_10_STOP_OFFSET  8  
#define AXI_JPEG_WR_QOS_THRESHOLD_01_START_LEN    4  
#define AXI_JPEG_WR_QOS_THRESHOLD_01_START_OFFSET 4  
#define AXI_JPEG_WR_QOS_THRESHOLD_01_STOP_LEN     4  
#define AXI_JPEG_WR_QOS_THRESHOLD_01_STOP_OFFSET  0  

#define AXI_JPEG_RD_QOS_SR_LEN                    2  
#define AXI_JPEG_RD_QOS_SR_OFFSET                 30 
#define AXI_JPEG_RD_QOS_MAX_LEN                   2  
#define AXI_JPEG_RD_QOS_MAX_OFFSET                28 
#define AXI_JPEG_RD_QOS_MIN_LEN                   2  
#define AXI_JPEG_RD_QOS_MIN_OFFSET                26 
#define AXI_JPEG_RD_QOS_THRESHOLD_11_START_LEN    4  
#define AXI_JPEG_RD_QOS_THRESHOLD_11_START_OFFSET 20 
#define AXI_JPEG_RD_QOS_THRESHOLD_11_STOP_LEN     4  
#define AXI_JPEG_RD_QOS_THRESHOLD_11_STOP_OFFSET  16 
#define AXI_JPEG_RD_QOS_THRESHOLD_10_START_LEN    4  
#define AXI_JPEG_RD_QOS_THRESHOLD_10_START_OFFSET 12 
#define AXI_JPEG_RD_QOS_THRESHOLD_10_STOP_LEN     4  
#define AXI_JPEG_RD_QOS_THRESHOLD_10_STOP_OFFSET  8  
#define AXI_JPEG_RD_QOS_THRESHOLD_01_START_LEN    4  
#define AXI_JPEG_RD_QOS_THRESHOLD_01_START_OFFSET 4  
#define AXI_JPEG_RD_QOS_THRESHOLD_01_STOP_LEN     4  
#define AXI_JPEG_RD_QOS_THRESHOLD_01_STOP_OFFSET  0  

#define AXI_JPEG_FORCE_CFG_CLK_ON_LEN       1  
#define AXI_JPEG_FORCE_CFG_CLK_ON_OFFSET    8  
#define AXI_JPEG_FORCE_DU_WR_CLK_ON_LEN     1  
#define AXI_JPEG_FORCE_DU_WR_CLK_ON_OFFSET  7  
#define AXI_JPEG_FORCE_DU_RD_CLK_ON_LEN     1  
#define AXI_JPEG_FORCE_DU_RD_CLK_ON_OFFSET  6  
#define AXI_JPEG_FORCE_AXI_WR_CLK_ON_LEN    1  
#define AXI_JPEG_FORCE_AXI_WR_CLK_ON_OFFSET 5  
#define AXI_JPEG_FORCE_AXI_RD_CLK_ON_LEN    1  
#define AXI_JPEG_FORCE_AXI_RD_CLK_ON_OFFSET 4  
#define AXI_JPEG_FORCE_NRWR_CLK_ON_LEN      1  
#define AXI_JPEG_FORCE_NRWR_CLK_ON_OFFSET   3  
#define AXI_JPEG_FORCE_NRRD_CLK_ON_LEN      1  
#define AXI_JPEG_FORCE_NRRD_CLK_ON_OFFSET   2  
#define AXI_JPEG_FORCE_VPWR_CLK_ON_LEN      1  
#define AXI_JPEG_FORCE_VPWR_CLK_ON_OFFSET   1  
#define AXI_JPEG_FORCE_VPRD_CLK_ON_LEN      1  
#define AXI_JPEG_FORCE_VPRD_CLK_ON_OFFSET   0  

#define AXI_JPEG_OTHER_RO_LEN    32 
#define AXI_JPEG_OTHER_RO_OFFSET 0  

#define AXI_JPEG_OTHER_RW_LEN    32 
#define AXI_JPEG_OTHER_RW_OFFSET 0  

#define AXI_JPEG_VPWR_LAST_PAGE_4_LEN          19 
#define AXI_JPEG_VPWR_LAST_PAGE_4_OFFSET       13 
 
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_4_LEN    1  
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_4_OFFSET 4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_4_LEN       4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_4_OFFSET    0  

#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_4_LEN    30 
#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_4_OFFSET 2  



#define AXI_JPEG_VPWR_LINE_WRAP_4_LEN      14 
#define AXI_JPEG_VPWR_LINE_WRAP_4_OFFSET   15 
#define AXI_JPEG_VPWR_LINE_START_WSTRB_4_LEN    4
#define AXI_JPEG_VPWR_LINE_START_WSTRB_4_OFFSET 11
#define AXI_JPEG_VPWR_LINE_STRIDE_4_LEN    11 
#define AXI_JPEG_VPWR_LINE_STRIDE_4_OFFSET 0  

#define AXI_JPEG_VPWR_PREFETCH_BYPASS_4_LEN                      1  
#define AXI_JPEG_VPWR_PREFETCH_BYPASS_4_OFFSET                   31 

#define AXI_JPEG_VP_WR_STOP_4_LEN                                1  
#define AXI_JPEG_VP_WR_STOP_4_OFFSET                             25 
#define AXI_JPEG_VP_WR_STOP_OK_4_LEN                             1  
#define AXI_JPEG_VP_WR_STOP_OK_4_OFFSET                          24 

#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_4_LEN                1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_4_OFFSET             18 
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_4_LEN               1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_4_OFFSET            17 
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_4_LEN    1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_4_OFFSET 16 

#define AXI_JPEG_VPWR_LAST_PAGE_5_LEN          19 
#define AXI_JPEG_VPWR_LAST_PAGE_5_OFFSET       13 

#define AXI_JPEG_VPWR_PIXEL_EXPANSION_5_LEN    1  
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_5_OFFSET 4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_5_LEN       4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_5_OFFSET    0  

#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_5_LEN    30 
#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_5_OFFSET 2  
 

 
#define AXI_JPEG_VPWR_LINE_WRAP_5_LEN      14 
#define AXI_JPEG_VPWR_LINE_WRAP_5_OFFSET   15 
#define AXI_JPEG_VPWR_LINE_START_WSTRB_5_LEN    4
#define AXI_JPEG_VPWR_LINE_START_WSTRB_5_OFFSET 11
#define AXI_JPEG_VPWR_LINE_STRIDE_5_LEN    11
#define AXI_JPEG_VPWR_LINE_STRIDE_5_OFFSET 0  

#define AXI_JPEG_VPWR_PREFETCH_BYPASS_5_LEN                      1  
#define AXI_JPEG_VPWR_PREFETCH_BYPASS_5_OFFSET                   31 
 
#define AXI_JPEG_VP_WR_STOP_5_LEN                                1  
#define AXI_JPEG_VP_WR_STOP_5_OFFSET                             25 
#define AXI_JPEG_VP_WR_STOP_OK_5_LEN                             1  
#define AXI_JPEG_VP_WR_STOP_OK_5_OFFSET                          24 
 
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_5_LEN                1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_5_OFFSET             18 
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_5_LEN               1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_5_OFFSET            17 
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_5_LEN    1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_5_OFFSET 16 
 

#define AXI_JPEG_VPWR_LAST_PAGE_6_LEN          19 
#define AXI_JPEG_VPWR_LAST_PAGE_6_OFFSET       13 
 
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_6_LEN    1  
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_6_OFFSET 4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_6_LEN       4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_6_OFFSET    0  

#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_6_LEN    30 
#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_6_OFFSET 2  



#define AXI_JPEG_VPWR_LINE_WRAP_6_LEN      14 
#define AXI_JPEG_VPWR_LINE_WRAP_6_OFFSET   15 
#define AXI_JPEG_VPWR_LINE_START_WSTRB_6_LEN    4
#define AXI_JPEG_VPWR_LINE_START_WSTRB_6_OFFSET 11
#define AXI_JPEG_VPWR_LINE_STRIDE_6_LEN    11
#define AXI_JPEG_VPWR_LINE_STRIDE_6_OFFSET 0  

#define AXI_JPEG_VPWR_PREFETCH_BYPASS_6_LEN                      1  
#define AXI_JPEG_VPWR_PREFETCH_BYPASS_6_OFFSET                   31 

#define AXI_JPEG_VP_WR_STOP_6_LEN                                1  
#define AXI_JPEG_VP_WR_STOP_6_OFFSET                             25 
#define AXI_JPEG_VP_WR_STOP_OK_6_LEN                             1  
#define AXI_JPEG_VP_WR_STOP_OK_6_OFFSET                          24 
 
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_6_LEN                1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_6_OFFSET             18 
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_6_LEN               1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_6_OFFSET            17 
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_6_LEN    1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_6_OFFSET 16 


#define AXI_JPEG_VPWR_LAST_PAGE_25_LEN          19 
#define AXI_JPEG_VPWR_LAST_PAGE_25_OFFSET       13 
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_25_LEN    1  
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_25_OFFSET 4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_25_LEN       4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_25_OFFSET    0  

#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_25_LEN    30 
#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_25_OFFSET 2  

#define AXI_JPEG_VPWR_LINE_WRAP_25_LEN      14 
#define AXI_JPEG_VPWR_LINE_WRAP_25_OFFSET   15 
#define AXI_JPEG_VPWR_LINE_START_WSTRB_25_LEN    4
#define AXI_JPEG_VPWR_LINE_START_WSTRB_25_OFFSET 11
#define AXI_JPEG_VPWR_LINE_STRIDE_25_LEN    11 
#define AXI_JPEG_VPWR_LINE_STRIDE_25_OFFSET 0  

#define AXI_JPEG_VPWR_PREFETCH_BYPASS_25_LEN                      1  
#define AXI_JPEG_VPWR_PREFETCH_BYPASS_25_OFFSET                   31 
#define AXI_JPEG_VP_WR_STOP_25_LEN                                1  
#define AXI_JPEG_VP_WR_STOP_25_OFFSET                             25 
#define AXI_JPEG_VP_WR_STOP_OK_25_LEN                             1  
#define AXI_JPEG_VP_WR_STOP_OK_25_OFFSET                          24 
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_25_LEN                1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_25_OFFSET             18 
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_25_LEN               1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_25_OFFSET            17 
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_25_LEN    1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_25_OFFSET 16 

#define AXI_JPEG_VPWR_LAST_PAGE_30_LEN          19 
#define AXI_JPEG_VPWR_LAST_PAGE_30_OFFSET       13 
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_30_LEN    1  
#define AXI_JPEG_VPWR_PIXEL_EXPANSION_30_OFFSET 4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_30_LEN       4  
#define AXI_JPEG_VPWR_PIXEL_FORMAT_30_OFFSET    0  

#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_30_LEN    30 
#define AXI_JPEG_VPWR_ADDRESS_FRAME_START_30_OFFSET 2  

#define AXI_JPEG_VPWR_LINE_WRAP_30_LEN      14 
#define AXI_JPEG_VPWR_LINE_WRAP_30_OFFSET   15 
#define AXI_JPEG_VPWR_LINE_START_WSTRB_30_LEN    4
#define AXI_JPEG_VPWR_LINE_START_WSTRB_30_OFFSET 11
#define AXI_JPEG_VPWR_LINE_STRIDE_30_LEN    11
#define AXI_JPEG_VPWR_LINE_STRIDE_30_OFFSET 0  

#define AXI_JPEG_VPWR_PREFETCH_BYPASS_30_LEN                      1  
#define AXI_JPEG_VPWR_PREFETCH_BYPASS_30_OFFSET                   31 
#define AXI_JPEG_VP_WR_STOP_30_LEN                                1  
#define AXI_JPEG_VP_WR_STOP_30_OFFSET                             25 
#define AXI_JPEG_VP_WR_STOP_OK_30_LEN                             1  
#define AXI_JPEG_VP_WR_STOP_OK_30_OFFSET                          24 
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_30_LEN                1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_PRESSURE_30_OFFSET             18 
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_30_LEN               1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_FLUX_CTRL_30_OFFSET            17 
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_30_LEN    1  
#define AXI_JPEG_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_30_OFFSET 16 


#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_4_LEN    4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_4_OFFSET 24 

#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_4_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_4_OFFSET      12 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_4_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_4_OFFSET      8  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_4_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_4_OFFSET      4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_4_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_4_OFFSET      0  


#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_5_LEN    4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_5_OFFSET 24 

#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_5_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_5_OFFSET      12 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_5_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_5_OFFSET      8  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_5_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_5_OFFSET      4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_5_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_5_OFFSET      0  


#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_6_LEN    4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_6_OFFSET 24 

#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_6_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_6_OFFSET      12 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_6_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_6_OFFSET      8  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_6_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_6_OFFSET      4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_6_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_6_OFFSET      0  

#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_25_LEN    4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_25_OFFSET 24 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_25_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_25_OFFSET      12 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_25_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_25_OFFSET      8  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_25_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_25_OFFSET      4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_25_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_25_OFFSET      0  

#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_30_LEN    4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_RELOAD_30_OFFSET 24 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_30_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_3_30_OFFSET      12 
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_30_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_2_30_OFFSET      8  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_30_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_1_30_OFFSET      4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_30_LEN         4  
#define AXI_JPEG_VPWR_ACCESS_LIMITER_0_30_OFFSET      0  

#define AXI_JPEG_VPRD_LAST_PAGE_4_LEN          19 
#define AXI_JPEG_VPRD_LAST_PAGE_4_OFFSET       13 
#define AXI_JPEG_VPRD_ALLOCATED_DU_4_LEN       5  
#define AXI_JPEG_VPRD_ALLOCATED_DU_4_OFFSET    5  
#define AXI_JPEG_VPRD_PIXEL_EXPANSION_4_LEN    1  
#define AXI_JPEG_VPRD_PIXEL_EXPANSION_4_OFFSET 4  
#define AXI_JPEG_VPRD_PIXEL_FORMAT_4_LEN       4  
#define AXI_JPEG_VPRD_PIXEL_FORMAT_4_OFFSET    0  

#define AXI_JPEG_VPRD_HORIZONTAL_BLANKING_4_LEN    8  
#define AXI_JPEG_VPRD_HORIZONTAL_BLANKING_4_OFFSET 16 
#define AXI_JPEG_VPRD_LINE_SIZE_4_LEN              13 
#define AXI_JPEG_VPRD_LINE_SIZE_4_OFFSET           0  

#define AXI_JPEG_VPRD_VERTICAL_BLANKING_4_LEN    8  
#define AXI_JPEG_VPRD_VERTICAL_BLANKING_4_OFFSET 16 
#define AXI_JPEG_VPRD_FRAME_SIZE_4_LEN           13 
#define AXI_JPEG_VPRD_FRAME_SIZE_4_OFFSET        0  

#define AXI_JPEG_VPRD_AXI_FRAME_START_4_LEN    30 
#define AXI_JPEG_VPRD_AXI_FRAME_START_4_OFFSET 2  

#define AXI_JPEG_VPRD_LINE_WRAP_4_LEN      13 
#define AXI_JPEG_VPRD_LINE_WRAP_4_OFFSET   16 
#define AXI_JPEG_VPRD_LINE_STRIDE_4_LEN    11
#define AXI_JPEG_VPRD_LINE_STRIDE_4_OFFSET 0  

#define AXI_JPEG_VPRD_PREFETCH_BYPASS_4_LEN                      1  
#define AXI_JPEG_VPRD_PREFETCH_BYPASS_4_OFFSET                   31 
#define AXI_JPEG_VP_RD_STOP_4_LEN                                1  
#define AXI_JPEG_VP_RD_STOP_4_OFFSET                             25 
#define AXI_JPEG_VP_RD_STOP_OK_4_LEN                             1  
#define AXI_JPEG_VP_RD_STOP_OK_4_OFFSET                          24 
#define AXI_JPEG_VP_RD_STOP_ENABLE_PRESSURE_4_LEN                1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_PRESSURE_4_OFFSET             18 
#define AXI_JPEG_VP_RD_STOP_ENABLE_FLUX_CTRL_4_LEN               1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_FLUX_CTRL_4_OFFSET            17 
#define AXI_JPEG_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_LEN    1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_OFFSET 16 

#define AXI_JPEG_VP_RD_DEBUG_4_LEN    32 
#define AXI_JPEG_VP_RD_DEBUG_4_OFFSET 0  

#define AXI_JPEG_VPRD_LAST_PAGE_8_LEN          19 
#define AXI_JPEG_VPRD_LAST_PAGE_8_OFFSET       13 

#define AXI_JPEG_VPRD_ALLOCATED_DU_8_LEN       5  
#define AXI_JPEG_VPRD_ALLOCATED_DU_8_OFFSET    5  
#define AXI_JPEG_VPRD_PIXEL_EXPANSION_8_LEN    1  
#define AXI_JPEG_VPRD_PIXEL_EXPANSION_8_OFFSET 4  
#define AXI_JPEG_VPRD_PIXEL_FORMAT_8_LEN       4  
#define AXI_JPEG_VPRD_PIXEL_FORMAT_8_OFFSET    0  


#define AXI_JPEG_VPRD_HORIZONTAL_BLANKING_8_LEN    8  
#define AXI_JPEG_VPRD_HORIZONTAL_BLANKING_8_OFFSET 16 

#define AXI_JPEG_VPRD_LINE_SIZE_8_LEN              13 
#define AXI_JPEG_VPRD_LINE_SIZE_8_OFFSET           0  

#define AXI_JPEG_RESERVED_1_LEN                  8  
#define AXI_JPEG_RESERVED_1_OFFSET               24 
#define AXI_JPEG_VPRD_VERTICAL_BLANKING_8_LEN    8  
#define AXI_JPEG_VPRD_VERTICAL_BLANKING_8_OFFSET 16 

#define AXI_JPEG_VPRD_FRAME_SIZE_8_LEN           13 
#define AXI_JPEG_VPRD_FRAME_SIZE_8_OFFSET        0  

#define AXI_JPEG_VPRD_AXI_FRAME_START_8_LEN    30 
#define AXI_JPEG_VPRD_AXI_FRAME_START_8_OFFSET 2  

#define AXI_JPEG_VPRD_LINE_WRAP_8_LEN      13 
#define AXI_JPEG_VPRD_LINE_WRAP_8_OFFSET   16 
 
#define AXI_JPEG_VPRD_LINE_STRIDE_8_LEN    11 
#define AXI_JPEG_VPRD_LINE_STRIDE_8_OFFSET 0  

#define AXI_JPEG_VPRD_PREFETCH_BYPASS_8_LEN                      1  
#define AXI_JPEG_VPRD_PREFETCH_BYPASS_8_OFFSET                   31 
 
#define AXI_JPEG_VP_RD_STOP_8_LEN                                1  
#define AXI_JPEG_VP_RD_STOP_8_OFFSET                             25 
#define AXI_JPEG_VP_RD_STOP_OK_8_LEN                             1  
#define AXI_JPEG_VP_RD_STOP_OK_8_OFFSET                          24 
 
#define AXI_JPEG_VP_RD_STOP_ENABLE_PRESSURE_8_LEN                1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_PRESSURE_8_OFFSET             18 
#define AXI_JPEG_VP_RD_STOP_ENABLE_FLUX_CTRL_8_LEN               1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_FLUX_CTRL_8_OFFSET            17 
#define AXI_JPEG_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_8_LEN    1  
#define AXI_JPEG_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_8_OFFSET 16 
 

#define AXI_JPEG_VP_RD_DEBUG_8_LEN    32 
#define AXI_JPEG_VP_RD_DEBUG_8_OFFSET 0  


#define AXI_JPEG_VPRD_ACCESS_LIMITER_RELOAD_4_LEN    4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_RELOAD_4_OFFSET 24 
#define AXI_JPEG_VPRD_ACCESS_LIMITER_3_4_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_3_4_OFFSET      12 
#define AXI_JPEG_VPRD_ACCESS_LIMITER_2_4_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_2_4_OFFSET      8  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_1_4_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_1_4_OFFSET      4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_0_4_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_0_4_OFFSET      0  


#define AXI_JPEG_VPRD_ACCESS_LIMITER_RELOAD_8_LEN    4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_RELOAD_8_OFFSET 24 

#define AXI_JPEG_VPRD_ACCESS_LIMITER_3_8_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_3_8_OFFSET      12 
#define AXI_JPEG_VPRD_ACCESS_LIMITER_2_8_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_2_8_OFFSET      8  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_1_8_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_1_8_OFFSET      4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_0_8_LEN         4  
#define AXI_JPEG_VPRD_ACCESS_LIMITER_0_8_OFFSET      0  


#define AXI_JPEG_NRRD_ENABLE_4_LEN                               1  
#define AXI_JPEG_NRRD_ENABLE_4_OFFSET                            31 
#define AXI_JPEG_RESERVED_3_LEN                                  5  
#define AXI_JPEG_RESERVED_3_OFFSET                               26 
#define AXI_JPEG_NR_RD_STOP_4_LEN                                1  
#define AXI_JPEG_NR_RD_STOP_4_OFFSET                             25 
#define AXI_JPEG_NR_RD_STOP_OK_4_LEN                             1  
#define AXI_JPEG_NR_RD_STOP_OK_4_OFFSET                          24 
#define AXI_JPEG_NR_RD_STOP_ENABLE_PRESSURE_4_LEN                1  
#define AXI_JPEG_NR_RD_STOP_ENABLE_PRESSURE_4_OFFSET             18 
#define AXI_JPEG_NR_RD_STOP_ENABLE_FLUX_CTRL_4_LEN               1  
#define AXI_JPEG_NR_RD_STOP_ENABLE_FLUX_CTRL_4_OFFSET            17 
#define AXI_JPEG_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_LEN    1  
#define AXI_JPEG_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_OFFSET 16 
#define AXI_JPEG_NRRD_ALLOCATED_DU_4_LEN                         5  
#define AXI_JPEG_NRRD_ALLOCATED_DU_4_OFFSET                      5  

#define AXI_JPEG_NR_RD_DEBUG_4_LEN    32 
#define AXI_JPEG_NR_RD_DEBUG_4_OFFSET 0  

#define AXI_JPEG_NRRD_ACCESS_LIMITER_RELOAD_4_LEN    4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_RELOAD_4_OFFSET 24 
#define AXI_JPEG_NRRD_ACCESS_LIMITER_3_4_LEN         4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_3_4_OFFSET      12 
#define AXI_JPEG_NRRD_ACCESS_LIMITER_2_4_LEN         4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_2_4_OFFSET      8  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_1_4_LEN         4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_1_4_OFFSET      4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_0_4_LEN         4  
#define AXI_JPEG_NRRD_ACCESS_LIMITER_0_4_OFFSET      0  

#define AXI_JPEG_SPARE_0_LEN    32 
#define AXI_JPEG_SPARE_0_OFFSET 0  

#define AXI_JPEG_SPARE_1_LEN    32 
#define AXI_JPEG_SPARE_1_OFFSET 0  

#define AXI_JPEG_SPARE_2_LEN    32 
#define AXI_JPEG_SPARE_2_OFFSET 0  

#define AXI_JPEG_SPARE_3_LEN    32 
#define AXI_JPEG_SPARE_3_OFFSET 0  

#define AXI_JPEG_VP_WR_DEBUG_4_LEN    32
#define AXI_JPEG_VP_WR_DEBUG_4_OFFSET 0

#define AXI_JPEG_VP_WR_DEBUG_5_LEN    32
#define AXI_JPEG_VP_WR_DEBUG_5_OFFSET 0

#define AXI_JPEG_VP_WR_DEBUG_6_LEN    32
#define AXI_JPEG_VP_WR_DEBUG_6_OFFSET 0

#define AXI_JPEG_VP_WR_DEBUG_25_LEN    32 
#define AXI_JPEG_VP_WR_DEBUG_25_OFFSET 0  

#define AXI_JPEG_VP_WR_DEBUG_30_LEN    32 
#define AXI_JPEG_VP_WR_DEBUG_30_OFFSET 0  

#define AXI_JPEG_DEBUG_0_LEN    32 
#define AXI_JPEG_DEBUG_0_OFFSET 0  

#define AXI_JPEG_DEBUG_1_LEN    32 
#define AXI_JPEG_DEBUG_1_OFFSET 0  

#define AXI_JPEG_DEBUG_2_LEN    32 
#define AXI_JPEG_DEBUG_2_OFFSET 0  

#define AXI_JPEG_DEBUG_3_LEN    32 
#define AXI_JPEG_DEBUG_3_OFFSET 0  

#define AXI_JPEG_DEBUG_4_LEN    32 
#define AXI_JPEG_DEBUG_4_OFFSET 0  

#define AXI_JPEG_DEBUG_5_LEN    32 
#define AXI_JPEG_DEBUG_5_OFFSET 0  

#define AXI_JPEG_DEBUG_6_LEN    32 
#define AXI_JPEG_DEBUG_6_OFFSET 0  

#define AXI_JPEG_DEBUG_7_LEN    32 
#define AXI_JPEG_DEBUG_7_OFFSET 0  

#define AXI_JPEG_DEBUG_8_LEN    32 
#define AXI_JPEG_DEBUG_8_OFFSET 0  

#define AXI_JPEG_DEBUG_9_LEN    32 
#define AXI_JPEG_DEBUG_9_OFFSET 0  

#define AXI_JPEG_DEBUG_10_LEN    32 
#define AXI_JPEG_DEBUG_10_OFFSET 0  

#define AXI_JPEG_DEBUG_11_LEN    32 
#define AXI_JPEG_DEBUG_11_OFFSET 0  

#define AXI_JPEG_DEBUG_12_LEN    32 
#define AXI_JPEG_DEBUG_12_OFFSET 0  

#define AXI_JPEG_DEBUG_13_LEN    32 
#define AXI_JPEG_DEBUG_13_OFFSET 0  

#define AXI_JPEG_DEBUG_14_LEN    32 
#define AXI_JPEG_DEBUG_14_OFFSET 0  

#define AXI_JPEG_DEBUG_15_LEN    32 
#define AXI_JPEG_DEBUG_15_OFFSET 0  

#endif // __AXI_JPEG_REG_OFFSET_FIELD_H__
